worker_processes 4;

events {
    worker_connections 1024;
}

http {
    tcp_nodelay on;
    keepalive_timeout 295s;
    server_tokens off;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80 default_server;

        # Proxy IRMA to local service
        location /irma/ {
            proxy_pass http://irma-server:8088/;
            proxy_set_header Host $host;
        }

        # Proxy everything else to Vite dev server
        location / {
            proxy_pass http://postguard-business:5173;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
}
